name = "JuliaConRegistry"
uuid = "7e621752-a872-11e9-000f-adc80f1c9326"
repo = "https://github.com/KristofferC/JuliaConRegistry.git"

description = """
Test registry for JuliaCon workshop
"""

[packages]
a8cc5b0e-0ffa-5ad4-8c14-923d3ee1735f = { name = "Crayons", path = "C/Crayons" }
