name = "JuliaConRegistry"
uuid = "7e621752-a872-11e9-000f-adc80f1c9326"
repo = "https://github.com/KristofferC/JuliaConRegistry.git"

description = """
Test registry for JuliaCon workshop
"""

[packages]
cb761652-754a-11e9-1d2d-6dcc2b16127a = { name = "AnotherTest", path = "A/AnotherTest" }
