name = "JuliaConRegistry"
uuid = "7e621752-a872-11e9-000f-adc80f1c9326"
repo = "https://github.com/KristofferC/JuliaConRegistry.git"

description = """
Test registry for JuliaCon workshop
"""

[packages]
742b3dd8-acad-11e9-0827-e3aaf7aff358 = { name = "MyPackage", path = "M/MyPackage" }
