name = "JuliaConRegistry"
uuid = "7e621752-a872-11e9-000f-adc80f1c9326"
repo = "https://github.com/KristofferC/JuliaConRegistry.git"

description = """
Test registry for JuliaCon workshop
"""

[packages]
725b21d0-acad-11e9-06a9-9f16682ff4d6 = { name = "MyPackage", path = "M/MyPackage" }
b4b65fde-acad-11e9-1657-e5fb27898dff = { name = "HTMLParser", path = "H/HTMLParser" }
